variables: secrets.yaml
templates:
  localtransmission:
    exists_series:
      - "{? paths.base ?}/torrent/downloads"
      - "{? paths.base ?}/torrent/incomplete"
    transmission:
      host: '{? transmission.host ?}'
      port: 9091
      username: '{? transmission.user ?}'
      password: '{? transmission.passwd ?}'
      addpaused: no
      path: "{? paths.base ?}/torrent/downloads"
  notifyseries:
    notify:
      entries:
        title: "A new episode of {{series_name}} is ready!"
        message: "{{series_id}} ({{quality}})"
        via:
          - pushbullet:
              api_key: '{? pb.apikey ?}'
  notifymovies:
    notify:
      entries:
        title: "A new movie is ready!"
        message: "{{imdb_name}}"
        via:
          - pushbullet:
              api_key: '{? pb.apikey ?}'
  refreshkodi:
    kodi_library:
      action: scan
      category: video
      url: '{? kodi.url ?}'
      port: 80

tasks:
  rtt:
    no_entries_ok: yes
    rss: "https://revolutiontt.me/rss.php?feed=dl&bookmarks=on&passkey={? rtt.passkey ?}"
    accept_all: yes
    template: localtransmission

  cleanup:
    no_entries_ok: yes
    accept_all: yes
    clean_transmission:
      host: '{? transmission.host ?}'
      port: 9091
      username: '{? transmission.user ?}'
      password: '{? transmission.passwd ?}'
      finished_for: 30 days
      min_ratio: 2
      delete_files: yes
      directories:
        - "{? paths.base ?}/torrent/downloads"

  unpack:
    priority: 5
    filesystem:
      path: "{? paths.base ?}/torrent/downloads"
      recursive: true
      regexp: .*\.(rar)$
    accept_all: true
    only_new: yes
    seen: local
    regexp:
      reject:
        - sample
    exec: unrar e -r -o- "{{location}}" "{? paths.base ?}/data/unsorted"

  sortseries:
    priority: 10
    no_entries_ok: yes
    metainfo_series: yes
    accept_all: yes
    seen: local
    filesystem:
      path: "{? paths.base ?}/torrent/downloads"
      recursive: 2
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4|m4v)$'
    require_field: series_name
    copy:
      to: "{? paths.base ?}/data/Shows/{{series_name}}/Season {{series_season}}/"
    template:
      - notifyseries
      - refreshkodi

  sortseries_extracted:
    priority: 10
    no_entries_ok: yes
    metainfo_series: yes
    accept_all: yes
    seen: local
    filesystem:
      path: "{? paths.base ?}/data/unsorted"
      recursive: false
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4|m4v)$'
    require_field: series_name
    move:
      to: "{? paths.base ?}/data/Shows/{{series_name}}/Season {{series_season}}/"
    template:
      - notifyseries
      - refreshkodi

  sortmovies:
    priority: 15
    no_entries_ok: yes
    require_field: imdb_url
    imdb:
      accept_languages:
        - english
        - french
        - spanish
    filesystem:
      path: "{? paths.base ?}/torrent/downloads"
      recursive: 2
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4|m4v)$'
    regexp:
      reject:
        - sample
        - Sample
    copy:
      to: "{? paths.base ?}/data/Movies"
    template:
      - notifymovies
      - refreshkodi

  sortmovies_extracted:
    priority: 15
    no_entries_ok: yes
    require_field: imdb_url
    imdb:
      accept_languages:
        - english
        - french
        - spanish
    filesystem:
      path: "{? paths.base ?}/data/unsorted"
      recursive: False
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4|m4v)$'
    move:
      to: "{? paths.base ?}/data/Movies"
    template:
      - notifymovies
      - refreshkodi
