secrets: secrets.yaml
templates:
  localtransmission:
    exists_series:
      - /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/downloads
      - /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/incomplete
    transmission:
      host: localhost
      port: 9091
      username: '{{secrets.transmission.user}}'
      password: '{{secrets.transmission.passwd}}'
      addpaused: no
      path: /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/downloads

tasks:
  rtt:
    rss: "https://revolutiontt.me/rss.php?feed=dl&bookmarks=on&passkey={{secrets.rtt.passkey}}"
    accept_all: yes
    template: localtransmission
    pushbullet:
      apikey: '{{secrets.pb.apikey}}'
      title: "Torrent added"
      body: "{{title}}"

  kat:
    rss: "https://kat.cr/bookmarks/rss/torrents/{{secrets.kat.passkey}}/"
    accept_all: yes
    template: localtransmission
    pushbullet:
      apikey: '{{secrets.pb.apikey}}'
      title: "Torrent added"
      body: "{{title}}"

  cleanup:
    clean_transmission:
      host: localhost
      port: 9091
      username: '{{secrets.transmission.user}}'
      password: '{{secrets.transmission.passwd}}'
      finished_for: 15 days
      min_ratio: 2
      delete_files: yes
      transmission_seed_limits: yes

  unpack:
    priority: 5
    filesystem:
      path: /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/downloads
      recursive: true
      regexp: .*\.(rar)$
    accept_all: true
    only_new: yes
    seen: local
    regexp:
      reject:
        - sample
    exec: unrar e -r -o- "{{location}}" /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/unsorted

  sort:
    priority: 10
    metainfo_series: yes
    accept_all: yes
    seen: local
    filesystem:
      path: /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/unsorted
      recursive: False
      retrieve: files
    require_field: series_name
    move:
      to: "/media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/Shows/{{series_name}}/Season {{series_season}}/"
    pushbullet:
      apikey: '{{secrets.pb.apikey}}'
      title: "A new episode is ready"
      body: "{{location|pathname}}"
    exec:
      on_exit:
        phase: /bin/bash /home/osmc/.flexget/xbmc-upd.sh
