variables: secrets.yaml
templates:
  localtransmission:
    exists_series:
      - /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/downloads
      - /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/incomplete
    transmission:
      host: localhost
      port: 9091
      username: '{? transmission.user ?}'
      password: '{? transmission.passwd ?}'
      addpaused: no
      path: /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/downloads

tasks:
  rtt:
    rss: "https://revolutiontt.me/rss.php?feed=dl&bookmarks=on&passkey={? rtt.passkey ?}"
    accept_all: yes
    template: localtransmission

  cleanup:
    clean_transmission:
      host: localhost
      port: 9091
      username: '{? transmission.user ?}'
      password: '{? transmission.passwd ?}'
      finished_for: 30 days
      min_ratio: 2
      delete_files: yes
      directories:
        - /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/downloads

  unpack:
    priority: 5
    filesystem:
      path: /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/downloads
      recursive: true
      regexp: .*\.(rar)$
    accept_all: true
    only_new: yes
    seen: local
    regexp:
      reject:
        - sample
    exec: unrar e -r -o- "{{location}}" /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/unsorted

  sort:
    priority: 10
    metainfo_series: yes
    accept_all: yes
    seen: local
    filesystem:
      path:
        - /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/torrent/downloads
      recursive: 2
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4|m4v)$'
    require_field: series_name
    copy:
      to: "/media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/Shows/{{series_name}}/Season {{series_season}}/"
    notify:
      entries:
        title: "A new episode of {{series_name}} is ready!"
        message: "{{series_id}}"
        via:
          - pushbullet:
              api_key: '{? pb.apikey ?}'

  sort_extracted:
    priority: 10
    metainfo_series: yes
    accept_all: yes
    seen: local
    filesystem:
      path:
        - /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/unsorted
      recursive: false
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4|m4v)$'
    require_field: series_name
    move:
      to: "/media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/Shows/{{series_name}}/Season {{series_season}}/"
    notify:
      entries:
        title: "A new episode of {{series_name}} is ready!"
        message: "{{series_id}}"
        via:
          - pushbullet:
              api_key: '{? pb.apikey ?}'

  sortmovies:
    priority: 15
    require_field: imdb_url
    imdb:
      accept_languages:
        - english
        - french
        - spanish
    filesystem:
      path: /media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/unsorted
      recursive: False
      retrieve: files
    move:
      to: "/media/05b91400-5855-4e9d-980c-b9e4f20f29dc/data/Movies"
    notify:
      entries:
        title: "A new movie is ready"
        message: "{{location|pathname}}"
        via:
          - pushbullet:
              api_key: '{? pb.apikey ?}'

  kodiupdate:
    priority: 20
    exec:
      on_exit:
        phase: /bin/bash /home/osmc/.flexget/xbmc-upd.sh
